name: artemis_flutter_ui_sdk_example
description: Demonstrates how to use the artemis_flutter_ui_sdk plugin.
publish_to: 'none'

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  artemis_flutter_ui_sdk:
    path: ../artemis_flutter_ui_sdk
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sdk_configurations.yaml
